num1 = int(input())
num2 = int(input())
num3 = int(input())
num4 = int(input())
num5 = int(input())
print(max(num1,num2,num3,num4,num5))
print(min(num1,num2,num3,num4,num5))
print((num1+num2+num3+num4+num5)/5)
